language: ruby
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: rbx-18mode
    - rvm: ree
    - rvm: jruby-18mode
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode # JRuby in 1.8 mode
  - rbx-18mode
  - rbx-19mode
  - ree
env:
  - "rack=1.3.4"
  - "rack=master"
  - "tilt=1.3.3"
  - "tilt=master"
